package funcionalidad;

public enum Pelis {
	IRON_MAN,
	EL_INCREIBLE_HULK,
	IRON_MAN_2,
	THOR,
	CAPITAN_AMERICA_EL_PRIMER_VENGADOR,
	LOS_VENGADORES,
	IRON_MAN_3,
	THOR_EL_MUNDO_OSCURO,
	CAPITAN_AMERICA_EL_SOLDADO_DE_INVIERNO,
	GUARDIANES_DE_LA_GALAXIA,
	LOS_VENGADORES_LA_ERA_DE_ULTRON,
	ANT_MAN,
	CAPITAN_AMERICA_CIVIL_WAR,
	DOCTOR_STRANGE,
	GUARDIANES_DE_LA_GALAXIA_VOL_2;
	
}
